default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: run black
        entry: poetry run black
        language: system
        types: [python]
        require_serial: true
        stages: [commit, manual]
      - id: isort
        name: run isort
        entry: poetry run isort
        language: system
        types: [python]
        require_serial: true
        stages: [commit, manual]
      - id: mypy
        name: run mypy
        entry: poetry run mypy ghome_foyer_api
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.5.1
    hooks:
      # Run `python-typing-update` hook manually from time to time
      # to update python typing syntax.
      # Will require manual work, before submitting changes!
      - id: python-typing-update
        stages: [manual]
        args:
          - --py39-plus
          - --force
          - --keep-updates
        files: ^.+\.pyi?$
