name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: Pre-commit
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Prepare and install deps
        uses: ./.github/actions/install-deps
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        name: Cache pre-commit hooks
        with:
          path: ~/.cache/pre-commit/
          key: >
            ${{ format('pre-commit-{0}-py{1}-{2}',
            runner.os,
            env.PYTHON_VERSION,
            hashFiles('.pre-commit-config.yaml')
            ) }}

      - name: Run pre-commit on all files
        run: |
          uvx pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Run python-typing-update
        run: |
          uvx pre-commit run --hook-stage manual python-typing-update --all-files --show-diff-on-failure --color=always
