name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    strategy:
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Prepare and install deps
        uses: ./.github/actions/install-deps
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish
